from abc import ABC, abstractmethod
from typing import AsyncGenerator, Dict, Any

class BaseLLMProvider(ABC):
    """
    Abstract Base Class for all LLM Providers in ResearchFlow AI.
    Every LLM provider must implement generate and generate_stream.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Unique key identifying the provider (e.g., 'gemini', 'nvidia', 'ollama')."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """The specific model name configured for this provider."""
        pass

    @abstractmethod
    async def generate(self, prompt: str, timeout: int = 30) -> str:
        """
        Generates a complete response for the given prompt.
        
        Args:
            prompt: The input prompt text.
            timeout: Timeout in seconds for the request.
            
        Returns:
            The generated text response.
        """
        pass

    @abstractmethod
    async def generate_stream(self, prompt: str) -> AsyncGenerator[str, None]:
        """
        Asynchronously yields text token chunks for the given prompt.
        
        Args:
            prompt: The input prompt text.
            
        Yields:
            Text chunks generated by the LLM.
        """
        pass

    @abstractmethod
    async def check_connection(self) -> Dict[str, Any]:
        """
        Checks the connection and configuration status of the provider.
        
        Returns:
            Dict containing status ('connected', 'not_configured', 'error'), 
            message, and model name.
        """
        pass
